In [1]:
import torch.nn as nn
import torch
import numpy as np

In [2]:
arr = torch.rand((2,10))

In [3]:
arr

tensor([[0.7112, 0.9121, 0.5585, 0.0496, 0.1785, 0.2599, 0.8242, 0.7842, 0.4904,
         0.9890],
        [0.6052, 0.7594, 0.0694, 0.1087, 0.5879, 0.8673, 0.6733, 0.5011, 0.3040,
         0.4792]])

In [4]:
mask = (arr<0.5)

In [5]:
mask

tensor([[False, False, False,  True,  True,  True, False, False,  True, False],
        [False, False,  True,  True, False, False, False, False,  True,  True]])

In [6]:
arr.masked_fill(mask,-float("inf"))

tensor([[0.7112, 0.9121, 0.5585,   -inf,   -inf,   -inf, 0.8242, 0.7842,   -inf,
         0.9890],
        [0.6052, 0.7594,   -inf,   -inf, 0.5879, 0.8673, 0.6733, 0.5011,   -inf,
           -inf]])

In [7]:
import json

In [8]:
with open("data/multi-woz-processed/data_for_damd.json") as f:
    data = json.load(f)

In [9]:
for dial_num, dial in data.items():
    for turn in dial["log"]:
        ptr_label = turn["ptr_label"].split(",")
        if len(ptr_label) > 31:
            print(dial_num, turn["turn_num"])