In [16]:
import torch.nn as nn
import torch
import numpy as np

In [2]:
arr = torch.rand((2,10))

In [3]:
arr

tensor([[0.9469, 0.6159, 0.0151, 0.2791, 0.1305, 0.1580, 0.7470, 0.3307, 0.2853,
         0.5119],
        [0.3731, 0.5165, 0.3065, 0.4116, 0.2944, 0.3229, 0.4055, 0.4240, 0.2926,
         0.2596]])

In [4]:
mask = (arr<0.5)

In [5]:
mask

tensor([[False, False,  True,  True,  True,  True, False,  True,  True, False],
        [ True, False,  True,  True,  True,  True,  True,  True,  True,  True]])

In [6]:
arr.masked_fill(mask,-float("inf"))

tensor([[0.9469, 0.6159,   -inf,   -inf,   -inf,   -inf, 0.7470,   -inf,   -inf,
         0.5119],
        [  -inf, 0.5165,   -inf,   -inf,   -inf,   -inf,   -inf,   -inf,   -inf,
           -inf]])

In [7]:
import json

In [17]:
with open("data/multi-woz-processed/data_for_damd.json") as f:
    data = json.load(f)

In [18]:
for dial_num, dial in data.items():
    for turn in dial["log"]:
        ptr_label = turn["ptr_label"].split(",")
        if len(ptr_label) > 31:
            print(dial_num, turn["turn_num"])

In [19]:
with open("data/multi-woz-processed/vocab.word2idx.json") as f:
    vocab = json.load(f)

In [22]:
for dial_num, dial in data.items():
    for turn in dial["log"]:
        ptr_label = turn["ptr_label"].split(",")
        for label in ptr_label:
            for word in label.split():
                if vocab[word] >= 3000:
                    print("{}-{}".format(dial_num, label))

pmul0741-18:23
pmul3863-02:45.
sng01940-mic
pmul0085-ital
pmul4459-18:06
pmul4459-18:06
sng01775-300
pmul3011-molecular gastonomy
pmul0735-1545
pmul0735-1545
sng01396-uro
sng0749-cott
sng0749-cott
pmul3465-duxford
sng02087-gener
sng0252-09:06
sng0252-07:21
sng0252-09:06
sng0252-07:21
mul2451-clu
mul2451-clu
pmul1714-lon
mul2467-20.00
mul2467-20.00
mul2196-20:36
mul2196-20:36
pmul3227-corpus cristi
sng01180-23:27
pmul0619-not mentionedc
pmul0810-19:57
pmul0810-19:57
mul1925-bo
pmul1849-08:44
pmul1849-08:44
sng02014-cas
sng02014-cas
mul2291-huntingd
mul2523-autu
pmul2527-lens
pmul2527-lens
pmul0944-seasame restaurant and bar
pmul2173-garde
pmul3129-16.30
pmul2562-grou
mul2626-wankworth hotel
mul2626-wankworth hotel
pmul2787-caridge belfrey
pmul2787-caridge belfrey
pmul2787-caridge belfrey
pmul2787-caridge belfrey
sng0579-kor
mul2592-g
mul1309-finders corner newmarket road
mul1309-finders corner newmarket road
mul1309-172 chestertown road
mul1309-finders corner newmarket road
mul1309-find